type: bdc

parameters:
    alpha0_diag_prior: 10
    mu0_prior: 0.0
    count_prior: 10
    upsilon0_prior: 10  # this is alpha in murphy's note
    beta0_prior: 0.5
    match_iou_cost: 2
    match_bbox_cost: 5  # l1 cost
